### ISSUE TITLE
Remove cache for package manager?

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/ansible-role-seal#17]
for example for CentOS
```sh
yum clean all
rm -rf /var/cache/yum
```

**Comment by myakove** [comment]
Optional or for every operation?

**Comment by KKoukiou** [comment]
I think we can just add this operation by default, no need to make it optional.

**Comment by myakove** [comment]
I think we should give an option for this, this operation can take time.
Let's say that I have 3 different tests and on each test, I need to install
some packages, I don't need/want to clean cache every few minutes since
it's unlikely that something changes in the repo. but forcing clean cache
will waste time.
Maybe set it to True by default and when not needed I can send
clear_cache=False.

**Comment by KKoukiou** [comment]
@myakove i see what you want to avoid here but take in mind that this reusing of cache will never ocour in your tests. When the cache gets > 1 week old, the yum will re-download them. And the images you are getting to run your tests again, have for sure exceeded this limit.

**Comment by myakove** [comment]
I meant few tests in the same run.

**Comment by myakove** [comment]
NM, now I saw that this is for ansible. Clean it please.
